# Generated by Django 2.1.1 on 2018-10-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('legal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DominioRestritoPor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificador.Dominio')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('legal', models.BooleanField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificador.Dominio')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaRestritoPor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificador.Pagina')),
                ('nome_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificador.Motivo')),
            ],
        ),
        migrations.AddField(
            model_name='dominiorestritopor',
            name='nome_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificador.Motivo'),
        ),
    ]
