# Generated by Django 2.1.1 on 2018-10-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dominio',
            old_name='legal',
            new_name='restrict',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='legal',
            new_name='restrict',
        ),
    ]
